services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: fastapiuser
      POSTGRES_PASSWORD: fastapipassword
      POSTGRES_DB: fastapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://fastapiuser:fastapipassword@db:5432/fastapidb"
      SECRET_KEY: "your-secret-key"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"

volumes:
  postgres_data:
